"""audit log table

Revision ID: 02bd9aecd63d
Revises: 82128b2f4573
Create Date: 2026-06-29 12:37:37.023982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02bd9aecd63d'
down_revision: Union[str, Sequence[str], None] = '82128b2f4573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('jti', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('notifications', 'pool_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_notifications_pool_id'), table_name='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_pool_id'), 'notifications', ['pool_id'], unique=False)
    op.alter_column('notifications', 'pool_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('audit_log')
    # ### end Alembic commands ###
