"""setup_models_init

Revision ID: 112e4d8732ae
Revises: fd06e0da5ca1
Create Date: 2026-06-17 03:35:01.675770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112e4d8732ae'
down_revision: Union[str, Sequence[str], None] = 'fd06e0da5ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=False),
    sa.Column('cost_per_member', sa.Float(), sa.Computed('total_cost / max_members', ), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pools_id'), 'pools', ['id'], unique=False)
    op.alter_column('users', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_pools_id'), table_name='pools')
    op.drop_table('pools')
    # ### end Alembic commands ###
