"""add host_id in pool_memebers

Revision ID: 3ca9738216db
Revises: db283cc92d4a
Create Date: 2026-06-21 23:57:31.775902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca9738216db'
down_revision: Union[str, Sequence[str], None] = 'db283cc92d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool_members', sa.Column('host_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_pool_members_host_id'), 'pool_members', ['host_id'], unique=False)
    op.create_foreign_key(None, 'pool_members', 'users', ['host_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pool_members', type_='foreignkey')
    op.drop_index(op.f('ix_pool_members_host_id'), table_name='pool_members')
    op.drop_column('pool_members', 'host_id')
    # ### end Alembic commands ###
