"""add pool_id in notifications

Revision ID: 82128b2f4573
Revises: 75ca3a594ee7
Create Date: 2026-06-23 09:10:53.083791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82128b2f4573'
down_revision: Union[str, Sequence[str], None] = '75ca3a594ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('pool_id', sa.UUID()))
    op.create_index(op.f('ix_notifications_pool_id'), 'notifications', ['pool_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'pools', ['pool_id'], ['pool_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_pool_id'), table_name='notifications')
    op.drop_column('notifications', 'pool_id')
    # ### end Alembic commands ###
