"""create index on is_active,created_at on pools table

Revision ID: d2b20526369b
Revises: f8d9a6d606e4
Create Date: 2026-07-08 10:29:52.316897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b20526369b'
down_revision: Union[str, Sequence[str], None] = 'f8d9a6d606e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_active_created_desc', 'pools', [sa.text('created_at DESC')], unique=False, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_active_created_desc', table_name='pools', postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###
