"""Create index on receiver_id and created at in notifications table 

Revision ID: d80f81e6efcd
Revises: 02bd9aecd63d
Create Date: 2026-07-08 07:02:32.539836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80f81e6efcd'
down_revision: Union[str, Sequence[str], None] = '02bd9aecd63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.create_index('idx_receiver_id_created_at', 'notifications', ['receiver_id', sa.text('created_at DESC')], unique=False, postgresql_concurrently=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index('idx_receiver_id_created_at', table_name='notifications', postgresql_concurrently=True)
    # ### end Alembic commands ###
