"""initial

Revision ID: db283cc92d4a
Revises: 
Create Date: 2026-06-21 01:33:53.674478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db283cc92d4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('pfp', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pools',
    sa.Column('pool_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('cost_per_member', sa.Numeric(precision=10, scale=2), sa.Computed('total_cost / max_members', ), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_members > 0', name='chq_maxmembers'),
    sa.CheckConstraint('total_cost > 0', name='chq_cost'),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pool_id')
    )
    op.create_index(op.f('ix_pools_host_id'), 'pools', ['host_id'], unique=False)
    op.create_table('pool_members',
    sa.Column('member_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'accepted', 'rejected', name='pool_status_enum'), server_default='requested', nullable=False),
    sa.Column('role', sa.Enum('host', 'member', name='pool_role_enum'), server_default='member', nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.pool_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('pool_id', 'user_id', name='unq_pool_user')
    )
    op.create_index(op.f('ix_pool_members_pool_id'), 'pool_members', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_members_user_id'), 'pool_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pool_members_user_id'), table_name='pool_members')
    op.drop_index(op.f('ix_pool_members_pool_id'), table_name='pool_members')
    op.drop_table('pool_members')
    op.drop_index(op.f('ix_pools_host_id'), table_name='pools')
    op.drop_table('pools')
    op.drop_table('notifications')
    op.drop_table('users')
    # ### end Alembic commands ###
