"""audit log table

Revision ID: f4f26ef7412e
Revises: 82128b2f4573
Create Date: 2026-06-29 12:36:27.053158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f26ef7412e'
down_revision: Union[str, Sequence[str], None] = '82128b2f4573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'pool_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_notifications_pool_id'), table_name='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_pool_id'), 'notifications', ['pool_id'], unique=False)
    op.alter_column('notifications', 'pool_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
