"""create index on unread_notification on notification table

Revision ID: f8d9a6d606e4
Revises: d80f81e6efcd
Create Date: 2026-07-08 08:24:17.907507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d9a6d606e4'
down_revision: Union[str, Sequence[str], None] = 'd80f81e6efcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_notifications_unread_by_user', 'notifications', ['receiver_id'], unique=False, postgresql_where=sa.text('is_read = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_unread_by_user', table_name='notifications', postgresql_where=sa.text('is_read = false'))
    # ### end Alembic commands ###
