"""add_posts_table_and_update_users

Revision ID: fd06e0da5ca1
Revises: df48ba063e5c
Create Date: 2026-06-17 03:25:10.030542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd06e0da5ca1'
down_revision: Union[str, Sequence[str], None] = 'df48ba063e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=False),
    sa.Column('cost_per_member', sa.Float(), sa.Computed('total_cost / max_members', ), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pools_id'), 'pools', ['id'], unique=False)
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    op.drop_index(op.f('ix_pools_id'), table_name='pools')
    op.drop_table('pools')
    # ### end Alembic commands ###

def upgrade():
    op.add_column(
        'users', 
        sa.Column(
            'disabled', 
            sa.Boolean(), 
            nullable=False, 
            server_default='false'  # This is the fix!
        )
    )